### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by deyvisonrocha** [luisdecker/X510UR-Hackintosh#1]
Hello guy!

I have a **X510UR BQ167T** and a strong ideia to hackintosh it. But I have any doubts:

- Did you need to replace any hardware?
- After install Mac OS and replace EFI did you need another configuration?

Thanks!

**Comment by luisdecker** [comment]
Hi!

I didn't replaced any hardware (yet, but pretending to buy a Broadcom wifi/bluetooth card), but I purchased a USB wifi dongle, since the Intel wifi/bt card that ships with X510UR isn't compatible with macOS. I have a **TP-Link Archer T1U AC450**, and is almost completely functional. The only con is that this adapter's driver for macOS can't connect to WPA2 Enterprise connections. 

This EFI files need to be on the clover folder of the installation media, and need to be copied to the EFI partition of your system after the installation. Olarila has good tutorials and installation files for vanilla hackintoshing.
